version: '3'

services:
  web:
    build: ./
    ports:
      - 8000
    environment:
      VIRTUAL_HOST: my-savings.test
    # only needed for local development
    command: npx adonis serve --dev
    volumes:
      - ./app:/usr/src/app/app
      - ./config:/usr/src/app/config
      - ./database:/usr/src/app/database
      - ./public:/usr/src/app/public
      - ./resources:/usr/src/app/resources
      - ./start:/usr/src/app/start
      - ./server.js:/usr/src/app/server.js
      - ./.env:/usr/src/app/.env
      - ./ace:/usr/src/app/ace
    links:
      - mysql
    # Enable if you want project to always boot up
    # restart: always

  mysql:
    image: mysql:5.7
    volumes:
      - ./.docker_local/.mysql/:/var/lib/mysql
      # - ./.docker_local/my_savings.sql.gz:/docker-entrypoint-initdb.d/my_savings.sql.gz
    ports:
      - 3306
    environment:
      MYSQL_USER: "my_savings_usr"
      MYSQL_PASSWORD: ""
      MYSQL_DATABASE: "my_savings_adonis"
      MYSQL_ROOT_PASSWORD: ""
    # Enable if you want project to always boot up
    # restart: always

# Your project docker-compose.yml must be on the same network as your dash.
networks:
  default:
    external:
      name: dash
